import matplotlib.pyplot as plt
##This script is generated by AI using the following prompts:
#I need a Python script that uses the matplotlib library.
# First, create two lists: one with the number of carbons for the first 10 linear alkanes
# and a second with their corresponding boiling point in Celsius.
# Then create a scatterplot of boiling point versus the number of carbons.
# Make sure the plot has a title and that the x and y axes are clearly labeled.

#Follow up prompt to include intermediate tick marks:
#Modify the y-axis tick marks to include markers every 25 degrees

#Nest prompt to generate the connecting line:
#Add a line to connect the points while still leaving the points visible

# Number of carbons in the first 10 linear alkanes
carbons = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Corresponding boiling points (°C)
boiling_points = [-161.5, -88.6, -42.1, -0.5, 36.1, 68.7, 98.4, 125.6, 150.8, 174.1]

# Create scatter plot
plt.plot(carbons, boiling_points, linestyle='-')
plt.scatter(carbons, boiling_points)

# Add title and axis labels
plt.title("Boiling Point vs. Number of Carbons for Linear Alkanes")
plt.xlabel("Number of Carbons")
plt.ylabel("Boiling Point (°C)")

# Set y-axis tick marks every 25 °C
plt.yticks(range(-175, 201, 25))

# Display the plot
plt.show()